baseURL = 'https://laioxy.github.io/'
disableKinds = ["taxonomy"]
languageCode = 'ja'
title = 'Lai-brary'

[page]
nextPrevInSectionSortOrder = 'asc'
nextPrevSortOrder = 'asc'

[params]
scenario = ["-", "Chapter-4クリア後", "Chapter-10から", "Chapter-10クリア後", "?", "?", "ギルド卒業後", "うみのリゾート解禁後"]
evolmethods1 = ["-", "Lv", "かしこさ", "道具", "テッポウオ仲間", "通信ケーブル"]
evolmethods2 = ["-", "つうしんケーブル", "攻撃＞防御", "防御＞攻撃", "攻撃＝防御", "たいようのリボン", "げっこうのリボン", "うつくしスカーフ", "ランダム", "ランダム", "オスである", "メスである", "げんしのちから習得", "ころがる習得", "ダブルアタック習得", "ものまね習得"]
iqgroups = ["A", "B", "C", "D", "E", "F", "G", "H", "未使用", "未使用", "I", "J", "未使用", "未使用", "未使用", "無効"]
movingtypes = ["通常", "?", "空中", "通過", "マグマ", "水上"]
