baseURL = 'https://laioxy.github.io/'
disableKinds = ["taxonomy"]
languageCode = 'ja'
title = 'Lai-brary'

[page]
nextPrevInSectionSortOrder = 'asc'
nextPrevSortOrder = 'asc'

[security]
allowContent = ["^text/html$", "^text/markdown$"]

[params]
scenario = [
    "-",
    "Chapter-5以降",
    "Chapter-10以降",
    "Chapter-11以降",
    "Chapter-19以降",
    "エンディング後",
    "ギルド卒業後",
    "うみのリゾート解禁後",
]
evolmethods1 = ["-", "Lv", "かしこさ", "道具", "テッポウオ仲間", "通信ケーブル"]
evolmethods2 = [
    "-",
    "つうしんケーブル",
    "攻撃＞防御",
    "防御＞攻撃",
    "攻撃＝防御",
    "たいようのリボン",
    "げっこうのリボン",
    "うつくしスカーフ",
    "ランダム",
    "ランダム",
    "オスである",
    "メスである",
    "げんしのちから習得",
    "ころがる習得",
    "ダブルアタック習得",
    "ものまね習得",
]
iqgroups = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "未使用",
    "未使用",
    "I",
    "J",
    "未使用",
    "未使用",
    "未使用",
    "未使用",
]
movingtypes = ["通常", "?", "空中", "通過", "マグマ", "水上"]

hiddenpowerPowerTable = [2, 4, 6, 7, 8, 9, 10, 13, 15, 17]
